### ISSUE TITLE
Slider input field has wrong width

### ISSUE THREAD

**Issue by lorumic** [canonical/react-components#1041]
This seems to be a problem introduced in the context of #1036 (version 0.49.0).

The slider input used to have a 5% width (verified checking out the commit tagged `v0.48.0`), and hence looked like this:

![Screenshot from 2024-02-09 15:41:16](https://github.com/canonical/react-components/assets/56583786/c650927f-54e5-4081-9297-57b41fe1afc5)

From version 0.49.0, it looks like this instead:

![image](https://github.com/canonical/react-components/assets/56583786/9cfd7550-5f5b-46c4-b5a1-d533e35f8cea)

@petermakowski Do you know why this is happening?

**Comment by petermakowski** [comment]
Very strange as there's no CSS code that could affect this in this change. I'll investigate.

**Comment by petermakowski** [comment]
@bartaz  Some background info I managed to figure out so far:
`%vf-input-elements` cannot be used without `@include vf-b-forms`, which includes global styles for input elements. 
https://github.com/canonical/vanilla-framework/blob/b4378c920f8bcb804db2ead64566ce3fa54636ae/scss/_base_forms.scss#L144

As soon as you add `@include vf-b-forms` to a component in order to extend `%vf-input-elements`, that as a result affects the order final CSS declarations and specificity which may alter styles in unrelated component.

## Screenshots

##### styles from base forms end up having higher specificity than those of a slider
![Google Chrome screenshot 001541@2x](https://github.com/canonical/react-components/assets/7452681/878e5e09-eeb1-4504-bfac-adabbaae47ad)

##### after removal of `@include vf-b-forms` import in `MultiSelect.scss` - styles declarations have expected order https://github.com/canonical/react-components/pull/1042
![Google Chrome screenshot 001543@2x](https://github.com/canonical/react-components/assets/7452681/51788a5b-5650-43e4-9333-e4bce6a0c1a0)

We could increase specificity of `.p-slider__input` alternatively, but the real fix would be to give an ability to _just_ import base input styles (`%vf-input-elements`) without global styles.

**Comment by bartaz** [comment]
> We could increase specificity of `.p-slider__input` alternatively, but the real fix would be to give an ability to _just_ import base input styles (`%vf-input-elements`) without global styles.

@petermakowski Thanks for looking into this and explaining the context. I think the issue is that we don't include Vanilla base styles in React components and try to add styles on top of that. That will not work. 

As mentioned here, to include individual compoents (or in our case, to build component styles on top of Vanilla), whole `vf-base` needs to be included (which includes `vf-b-forms`, among others). That's the only way to make sure all the necessary global and base styles are included in correct source order.

I don't know how to align that with React components. Obviously we don't want each component to separately include `vf-base`, but it seems in the React components styles we need the base included, so that components can extend anything from it.
