### ISSUE TITLE
Release notes don't mention all released PRs

### ISSUE THREAD

**Issue by bartaz** [canonical/react-components#1055]
It seems that release notes on GH only list a single merged PR, not everything that is part of the release.

For example release 0.50.6: https://github.com/canonical/react-components/releases/tag/v0.50.6

It included at least: 

- https://github.com/canonical/react-components/pull/1052 (that is mentioned)
- https://github.com/canonical/react-components/pull/1010#issuecomment-2006572458 (that is not mentioned)

Not sure how the current automatic releases with semantic-release work?

**Comment by bartaz** [comment]
There is some "release notes generator" step, maybe that's where the issue is?

```
[9:51:30 AM] [semantic-release] › ℹ  The next release version is 0.50.6
[9:51:30 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:51:30 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:51:30 AM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[9:51:30 AM] [semantic-release] [@semantic-release/changelog] › ℹ  Create /home/runner/work/react-components/react-components/CHANGELOG.md
```

**Comment by jmuzina** [comment]
The last release that had multiple PRs was [0.47.3](https://github.com/canonical/react-components/releases/tag/v0.47.3).

The release notes generator was updated in #1030 . This PR bumped the release labeller from v4 to v5, perhaps this caused our issue?

@mas-who do you know anything more about this?

**Comment by mas-who** [comment]
> The last release that had multiple PRs was [0.47.3](https://github.com/canonical/react-components/releases/tag/v0.47.3).
> 
> The release notes generator was updated in #1030 . This PR bumped the release labeller from v4 to v5, perhaps this caused our issue?
> 
> @mas-who do you know anything more about this?

@jmuzina yes the 0.47.3 release was the last release prior to semantic-release was enabled in #1024. Since semantic-release triggers a release workflow on push to main, it is expected that every merged PR would be a separate release. PR #1030 fixed the issue of [pull-request-labeler](https://github.com/actions/labeler/tree/main#pull-request-labeler) github action breaking CI and is not related to semantic-release.

There is a [guide](https://github.com/canonical/react-components/blob/v0.50.6/HACKING.md#pull-requests) on how PR titles should be formulated for semantic-release to trigger a release, I think perhaps that is related to the issue @bartaz raised?

@petermakowski any thoughts on this?

**Comment by bartaz** [comment]
Let's continue using semantic release defaults and see if there are any issues with that in future.
