### ISSUE TITLE
Inconsistent icon direction on sortable table

### ISSUE THREAD

**Issue by andesol** [canonical/react-components#1107]
After https://github.com/canonical/vanilla-framework/pull/5135 that inverted the icons on the sortable table, seems like it needs to be updated on the react components as well, otherwise the direction doesn't match.

Compare this example:
https://vanillaframework.io/docs/examples/patterns/tables/table-sortable?theme=light

With this one:
https://canonical.github.io/react-components/?path=/story/components-maintable--sortable

**Comment by jmuzina** [comment]
I believe this was fixed by #1096 (React Components needed to be updated to use [v4.13.0](https://github.com/canonical/vanilla-framework/releases/tag/v4.13.0) or later. Previously React Components was using [v4.11.0](https://github.com/canonical/vanilla-framework/releases/tag/v4.11.0). 

@andesol Is this issue still occurring for you?

**Comment by andesol** [comment]
@jmuzina Works consistently now :+1:
