### ISSUE TITLE
`MultiSelect`: Dropdown list should have same margin at top and bottom

### ISSUE THREAD

**Issue by ethanashaw** [canonical/react-components#1164]
The `MultiSelect` dropdown list has a noticeably smaller margin at the top.

### Before 
![image](https://github.com/user-attachments/assets/279a74ce-de90-424c-a1ef-5087176a0e9c)

### After
![image](https://github.com/user-attachments/assets/0ae02beb-4f8e-4bcf-858e-688c080948b2)

**Comment by jmuzina** [comment]
`.multi-select__dropdown-list` defines a 4px bottom margin, but no top margin.
https://github.com/canonical/react-components/blob/86e2b2a7e2eaf1e9734a1d554af7102c781fe6c3/src/components/MultiSelect/MultiSelect.scss#L55-L60

Adding `margin-top: $sph--x-small;` should fix the issue.

We still need to check with design however to see whether this spacing difference is intentional. @lyubomir-popov can you have a look please?

**Comment by bartaz** [comment]
I'd suggest just making a PR and getting a design review.

**Comment by lyubomir-popov** [comment]
looks good, thanks foir spotting @ethanashaw and thanks for fixin @jmuzina
