### ISSUE TITLE
Filter panel opens when a chip is removed

### ISSUE THREAD

**Issue by ilayda21** [canonical/react-components#621]
### Description of the bug
When a chip is removed from the search and filter component,  filter panel is displayed. 

### Steps to reproduce the behavior:
- Go to https://canonical-web-and-design.github.io/react-components/?path=/story/search-and-filter--default-story
- Add a filter.
- Remove the chip.
- Filter panel opens.

### Expected behavior
After deleting a chip, filter panel shouldn't open.

![1](https://user-images.githubusercontent.com/24393395/137158310-2f78b7f3-51da-4c39-bf13-99c6e822b428.gif)

**Comment by marinacastejon** [comment]
We discussed about it in the squad. While it might make sense in some cases to encourage people to select another filter, in many cases removing filter should just update the information displayed (in our case a graph) without re-opening the filter panel again. In e-commerce this is the standard. In the IBM Carbon design system they also follow that, [see example](https://cloud.ibm.com/docs/search?q=cloud).
Therefore, we would like a version of this component that does not open the panel when removing the filter.
@bartaz @ziheliu214

**Comment by bartaz** [comment]
It will be discussed in WG in canonical-web-and-design/vanilla-framework#4076

**Comment by clagom** [comment]
- The current implementation of the component didn't take into consideration the UX specs: https://discourse.ubuntu.com/t/behaviour-delete-a-filter-chip/21546
In particular:
- The input field should include chips (currently in a different container, separated from the input field)
- Users should be able to use backspace to remove chips (currently is not possible because of the separation of the elements)
- If the focus is on the input field, it should open the panel underneath
- If there's no focus on the input field, the panel shouldn't open
- Clicking with the cursor on the "X" to remove a chip from the input field shouldn't therefore trigger the panel to open

WG: please refer to the UX specifications in order to iterate on the implementation of the component.
CC @bartaz @sowasred2012

**Comment by ziheliu214** [comment]
> > Clicking with the cursor on the "X" to remove a chip from the input field shouldn't therefore trigger the panel to open
> 
> I believe that is opposite to the UX spec:
> 
> ![image](https://user-images.githubusercontent.com/1413534/138096699-a5e611fe-a117-4d70-ac38-92166e1776fd.png)

You are right, there should be a middle stage between the last 2 interaction stage - after removing the chip, the field remains inactive. Once on focus (with the blue outline) the panel is open.

**Comment by clagom** [comment]
Yes, what @ziheliu214 specified. Can you please update the specs to be clearer in that sense Zihe, thanks!

**Comment by hatched** [comment]
> Users should be able to use backspace to remove chips (currently is not possible because of the separation of the elements). This is also an accessibility issue.

This isn't why it's not possible, you can't place or style elements inside an input element. 

If we want to allow you to use the backspace button to delete the chips we need to listen for the backspace button when the input is focused, if the cursor location is at 0 and there are active chips then remove the last one in the list. This feature was just never implemented.

This will need some accessibility investigation as I'm not sure how that would "read" as the element would be removed from outside the input.

**Comment by ziheliu214** [comment]
> Yes, what @ziheliu214 specified. Can you please update the specs to be clearer in that sense Zihe, thanks!

cc @anthonydillon 
updated the behaviour discourse post: https://discourse.ubuntu.com/t/behaviour-delete-a-filter-chip/21546
