### ISSUE TITLE
Update Storybook to use webpack v5

### ISSUE THREAD

**Issue by bartaz** [canonical/react-components#670]
Some of the dependency updates coming from renovate require webpack v5, but storybook works with webpack v4 by default.

There is an [opt-in support for webpack v5](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5) but for some reason following the migration guide doesn't work out of the box in our setup. We get some obscure error: 

`Error: Template execution failed: ReferenceError: options is not defined`

I did spend some time trying to figure out why it happens but didn't find anything obvious, google/stackoverflow doesn't give any obvious solutions either. It will require some longer investigation to see what needs to be fixed to use webpack 5 with storybook in our project.

**Comment by bebraw** [comment]
FWIW, it's crashing because the EJS template in question has a line like `<title><%= options.title || 'Storybook'%></title>`. In **html-webpack-plugin** 5, it expects `<title><%= htmlWebpackPlugin.options.title %></title>` instead.

To resolve, I think you'll have to make sure you are running Storybook 6.4 at least as this is coming from **@storybook/core-common**.

**Comment by YonathanB** [comment]
You're not the omly one facing that issue.
BTW I have a totally different configuration (i m using angular).
Seems that problems come from http-webpack-plugin
